#if !canImport(ObjectiveC)
import XCTest

extension ThreadSafetyTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ThreadSafetyTests = [
        ("testCustomExceptionsThreadSafety", testCustomExceptionsThreadSafety),
        ("testHyphenatorCacheThreadSafety", testHyphenatorCacheThreadSafety),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ThreadSafetyTests.__allTests__ThreadSafetyTests),
    ]
}
#endif
