#if !canImport(ObjectiveC)
import XCTest

extension PerformanceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PerformanceTests = [
        ("testConcurrentPerformance", testConcurrentPerformance),
        ("testIndependentPerformance", testIndependentPerformance),
        ("testLongWordPerformance", testLongWordPerformance),
        ("testSequentialPerformance", testSequentialPerformance),
        ("testSpeed1Constitution", testSpeed1Constitution),
        ("testSpeed2PrideAndPrejudice", testSpeed2PrideAndPrejudice),
        ("testSpeed3GreatExpectations", testSpeed3GreatExpectations),
        ("testSpeed4WarAndPeace", testSpeed4WarAndPeace),
        ("testSpeed5KingJamesBible", testSpeed5KingJamesBible),
        ("testSpeed6Clarissa", testSpeed6Clarissa),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(PerformanceTests.__allTests__PerformanceTests),
    ]
}
#endif
