#if !canImport(ObjectiveC)
import XCTest

extension HyphenationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__HyphenationTests = [
        ("testBadPatternErrors", testBadPatternErrors),
        ("testCacheInvalidation", testCacheInvalidation),
        ("testCaseInsensitivity", testCaseInsensitivity),
        ("testCustomExceptions", testCustomExceptions),
        ("testCustomPatternFiles", testCustomPatternFiles),
        ("testExceptions", testExceptions),
        ("testHyphenatorCopy", testHyphenatorCopy),
        ("testMultiWordHyphenation", testMultiWordHyphenation),
        ("testPatternMatching", testPatternMatching),
        ("testPreHyphenatedWords", testPreHyphenatedWords),
        ("testSingleWordHyphenation", testSingleWordHyphenation),
        ("testSubstringHyphenation", testSubstringHyphenation),
        ("testUnhyphenateMethod", testUnhyphenateMethod),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(HyphenationTests.__allTests__HyphenationTests),
    ]
}
#endif
